import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as readline from 'readline';
import { spawnSync } from 'child_process';

const DEFAULT_CONFIG = {
  version: '1',
  policies: {
    allowedPaths: [
      './src/**',
      './data/**',
      './README.md',
      './CLAUDE.md'
    ],
    blockedPaths: [
      './.env',
      './.env.*',
      './package-lock.json',
      '/etc/**',
      '/usr/**'
    ],
    blockedCommands: [
      'rm -rf',
      'DROP TABLE',
      'DROP DATABASE',
      'chmod 777',
      'regex:\\|\\s*bash',
      'regex:\\|\\s*sh\\b',
      'regex:\\$\\(curl',
      'regex:\\$\\(wget',
      'wget '
    ],
    requireApproval: [
      './src/db/**',
      './waymark.config.json'
    ],
    maxBashOutputBytes: 10000
  }
};

const WAYMARK_MARKER = '<!-- waymark -->';

function kebabCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[\s_]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function generateClaudeMd(projectName: string, port: number): string {
  return `---
# ⚠️ WAYMARK ACTIVE — MANDATORY INSTRUCTIONS

## You are operating under Waymark agent control

Waymark is active in this project (${projectName}).
All file and shell operations MUST go through
Waymark MCP tools. No exceptions.

## MANDATORY tool usage

You MUST replace ALL built-in file and shell
operations with Waymark MCP equivalents:

| Operation              | Built-in (DO NOT USE) | Waymark (ALWAYS USE) |
|------------------------|-----------------------|----------------------|
| Write or edit a file   | write_file            | mcp__waymark-${projectName}__write_file |
| Read a file            | read_file             | mcp__waymark-${projectName}__read_file  |
| Run shell commands     | bash / run_command    | mcp__waymark-${projectName}__bash       |

This applies to ALL tasks in this project —
refactoring, creating files, running tests,
installing packages, git operations, everything.

## What Waymark does with each action

- Allowed paths → executes normally, logged
- Blocked paths → stopped, you will see why
- Sensitive paths → held for human approval,
  do not retry, tell the user to check dashboard

## If a Waymark tool returns a block decision

Accept the block. Do not attempt to work around it
using built-in tools. Tell the user what was blocked
and why. Suggest they update waymark.config.json
if the block was unintended.

## If Waymark MCP tools are unavailable

Do NOT fall back to built-in file tools.
Stop and tell the user:

"Waymark MCP server is not running for this project.
Please run in your terminal:
  npx @way_marks/cli start

Then restart Claude Code and try again."

## Dashboard

All actions are visible at: http://localhost:${port}
Approve pending actions there.
Roll back any write there.

## This file was generated by Waymark
Do not delete or modify this file.
It controls how Claude Code behaves in this project.
---
`;
}

function prompt(question: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    rl.question(question, answer => { rl.close(); resolve(answer.trim()); });
  });
}

function getClaudeDesktopConfigPath(): string {
  const platform = process.platform;
  if (platform === 'darwin') {
    return path.join(os.homedir(), 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json');
  } else if (platform === 'win32') {
    return path.join(process.env.APPDATA || os.homedir(), 'Claude', 'claude_desktop_config.json');
  } else {
    return path.join(os.homedir(), '.config', 'Claude', 'claude_desktop_config.json');
  }
}

function resolveServerBin(): string {
  try {
    return require.resolve('@way_marks/server/dist/mcp/server.js');
  } catch {
    return path.resolve(__dirname, '../../../server/dist/mcp/server.js');
  }
}

export async function run(): Promise<void> {
  const projectRoot = process.cwd();
  const projectName = kebabCase(path.basename(projectRoot));
  const mcpKey = `waymark-${projectName}`;
  const dbPath = path.join(projectRoot, '.waymark', 'waymark.db');
  const defaultPort = 3001;

  console.log(`Initializing Waymark in: ${projectRoot}`);

  // Step 1 — Detect project
  const hasPackageJson = fs.existsSync(path.join(projectRoot, 'package.json'));
  const hasGit = fs.existsSync(path.join(projectRoot, '.git'));
  if (!hasPackageJson && !hasGit) {
    console.warn('Warning: No package.json or .git found. Continuing anyway.');
  }

  // Step 2 — Install @way_marks/server (skip if already resolvable or in monorepo)
  let serverBin: string;
  try {
    serverBin = require.resolve('@way_marks/server/dist/mcp/server.js');
    console.log('✓ @way_marks/server already installed');
  } catch {
    const monorepoFallback = path.resolve(__dirname, '../../../server/dist/mcp/server.js');
    if (fs.existsSync(monorepoFallback)) {
      serverBin = monorepoFallback;
      console.log('✓ Using local @way_marks/server (monorepo)');
    } else {
      console.log('Installing @way_marks/server...');
      const result = spawnSync('npm', ['install', '--save-dev', '@way_marks/server'], {
        stdio: 'inherit',
        cwd: projectRoot
      });
      if (result.status !== 0) {
        console.error('Failed to install @way_marks/server');
        process.exit(1);
      }
      serverBin = resolveServerBin();
    }
  }

  // Step 3 — Create waymark.config.json
  const configPath = path.join(projectRoot, 'waymark.config.json');
  if (fs.existsSync(configPath)) {
    const answer = await prompt('waymark.config.json exists. Overwrite? (y/N) ');
    if (answer.toLowerCase() !== 'y') {
      console.log('Keeping existing waymark.config.json');
    } else {
      fs.writeFileSync(configPath, JSON.stringify(DEFAULT_CONFIG, null, 2) + '\n');
      console.log('✓ Created waymark.config.json');
    }
  } else {
    fs.writeFileSync(configPath, JSON.stringify(DEFAULT_CONFIG, null, 2) + '\n');
    console.log('✓ Created waymark.config.json');
  }

  // Step 4 — Create/append CLAUDE.md
  const claudeMdPath = path.join(projectRoot, 'CLAUDE.md');
  const claudeMdContent = generateClaudeMd(projectName, defaultPort);
  if (fs.existsSync(claudeMdPath)) {
    const existing = fs.readFileSync(claudeMdPath, 'utf8');
    if (existing.includes(WAYMARK_MARKER)) {
      console.log('✓ CLAUDE.md already has Waymark section');
    } else {
      fs.appendFileSync(claudeMdPath, `\n${WAYMARK_MARKER}\n${claudeMdContent}`);
      console.log('✓ Appended Waymark section to CLAUDE.md');
    }
  } else {
    fs.writeFileSync(claudeMdPath, `${WAYMARK_MARKER}\n${claudeMdContent}`);
    console.log('✓ Created CLAUDE.md — Claude Code will now use Waymark automatically');
  }

  // Step 5 — Update .gitignore
  const gitignorePath = path.join(projectRoot, '.gitignore');
  const gitignoreContent = fs.existsSync(gitignorePath)
    ? fs.readFileSync(gitignorePath, 'utf8')
    : '';
  const linesToAdd = ['.waymark/', 'waymark.db', 'data/waymark.db']
    .filter(line => !gitignoreContent.includes(line));
  if (linesToAdd.length > 0) {
    const section = '\n# Waymark\n' + linesToAdd.join('\n') + '\n';
    fs.appendFileSync(gitignorePath, section);
    console.log('✓ Updated .gitignore');
  } else {
    console.log('✓ .gitignore already up to date');
  }

  // Step 6 — Register MCP in both Claude configs
  const nodeBin = process.execPath;
  const mcpEntry = {
    command: nodeBin,
    args: [serverBin, '--project-root', projectRoot, '--db-path', dbPath]
  };

  // Claude Desktop config — add/update this project's entry only
  const desktopConfigPath = getClaudeDesktopConfigPath();
  try {
    const desktopDir = path.dirname(desktopConfigPath);
    if (!fs.existsSync(desktopDir)) fs.mkdirSync(desktopDir, { recursive: true });
    const desktopConfig = fs.existsSync(desktopConfigPath)
      ? JSON.parse(fs.readFileSync(desktopConfigPath, 'utf8'))
      : { mcpServers: {} };
    if (!desktopConfig.mcpServers) desktopConfig.mcpServers = {};
    desktopConfig.mcpServers[mcpKey] = mcpEntry;
    fs.writeFileSync(desktopConfigPath, JSON.stringify(desktopConfig, null, 2) + '\n');
    console.log(`✓ Registered MCP server "${mcpKey}" in Claude Desktop config`);
  } catch (err: any) {
    console.warn(`Warning: Could not update Claude Desktop config: ${err.message}`);
  }

  // .mcp.json (Claude Code project-level)
  const mcpJsonPath = path.join(projectRoot, '.mcp.json');
  try {
    const mcpJson = fs.existsSync(mcpJsonPath)
      ? JSON.parse(fs.readFileSync(mcpJsonPath, 'utf8'))
      : { mcpServers: {} };
    if (!mcpJson.mcpServers) mcpJson.mcpServers = {};
    mcpJson.mcpServers[mcpKey] = { type: 'stdio', ...mcpEntry, cwd: projectRoot };
    fs.writeFileSync(mcpJsonPath, JSON.stringify(mcpJson, null, 2) + '\n');
    console.log(`✓ Created/updated .mcp.json for Claude Code`);
  } catch (err: any) {
    console.warn(`Warning: Could not update .mcp.json: ${err.message}`);
  }

  // Step 7 — Success summary
  const col = 43;
  const pad = (s: string) => s + ' '.repeat(Math.max(0, col - 2 - s.length));
  console.log('');
  console.log('┌' + '─'.repeat(col) + '┐');
  console.log(`│ ${pad('✅ Waymark initialized')} │`);
  console.log(`│ ${pad('')} │`);
  console.log(`│ ${pad(`Project: ${projectName}`)} │`);
  console.log(`│ ${pad('Database: .waymark/waymark.db')} │`);
  console.log(`│ ${pad(`MCP key: ${mcpKey}`)} │`);
  console.log(`│ ${pad('')} │`);
  console.log(`│ ${pad('Files created:')} │`);
  console.log(`│ ${pad('  waymark.config.json')} │`);
  console.log(`│ ${pad('  CLAUDE.md')} │`);
  console.log(`│ ${pad('  .waymark/ (gitignored)')} │`);
  console.log(`│ ${pad('')} │`);
  console.log(`│ ${pad('Next steps:')} │`);
  console.log(`│ ${pad('1. Run: npx @way_marks/cli start')} │`);
  console.log(`│ ${pad('2. Restart Claude Code')} │`);
  console.log(`│ ${pad('3. Open this project in Claude')} │`);
  console.log(`│ ${pad('4. Dashboard: http://localhost:3001')} │`);
  console.log(`│ ${pad('   (port may differ if 3001 is taken)')} │`);
  console.log(`│ ${pad('')} │`);
  console.log(`│ ${pad('Waymark is now always-on in this')} │`);
  console.log(`│ ${pad('project. Claude will use Waymark')} │`);
  console.log(`│ ${pad('tools automatically via CLAUDE.md')} │`);
  console.log('└' + '─'.repeat(col) + '┘');
}
